version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: mongo_banquito
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  turno:
    build:
      context: ./turno
    container_name: ms_turno
    ports:
      - "8083:8083"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=banquito_ventanillas

  transaccion:
    build:
      context: ./transaccion
    container_name: ms_transaccion
    ports:
      - "8084:8084"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=banquito_ventanillas
      - TURNO_SERVICE_URL=http://ms_turno:8083

volumes:
  mongo_data: 